---
title: "1_GENIE_dataprep_3panels"
author: "Sara Horie"
date: "2022/01/23"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library}
library(tidyverse)
library(dplyr)
library(readxl)
library(RColorBrewer)
library(viridis)
library(ggplot2)
library(plotly)
library(ggrepel)
```

```{r}
outdir_pdf <- str_glue("result/1_genie/table/1_panel_selection")
dir.create(outdir_pdf, recursive = TRUE, showWarnings = FALSE)

# table
outdir_table <- str_glue("result/1_genie/table/1_panel_selection")
dir.create(outdir_table, recursive = TRUE, showWarnings = FALSE)

dir.create(str_glue("{outdir_table}/1_sample_sheet/1_dataprep/"), recursive = TRUE, showWarnings = FALSE)
dir.create(str_glue("{outdir_table}/2_mutation_sheet/1_dataprep/"), recursive = TRUE, showWarnings = FALSE)

# dir.create("result/1_genie/table/1_panel_selection/1_sample_sheet/1_dataprep/", recursive = TRUE, showWarnings = FALSE)
# dir.create("result/1_genie/table/1_panel_selection/2_mutation_sheet/1_dataprep/", recursive = TRUE, showWarnings = FALSE)
```

# 1. Dataset preparation
```{r read in GENIE data}
# read in GENIE data
# getwd()
GENIE_sample_file <- read_tsv("../../data/genie/Release_14.0_public/data_clinical_sample.txt", skip  = 4)
nrow(GENIE_sample_file)
GENIE_sample_file %>% distinct(PATIENT_ID) %>% nrow()  #160965

GENIE_sample_file %>% 
  count(SEQ_ASSAY_ID) %>% 
  arrange(-n)

#added col_characters##
GENIE_mut_file <- read_tsv("../../data/genie/Release_14.0_public/data_mutations_extended.txt",
                           col_types = cols(Chromosome = col_character(), 
                                            Tumor_Seq_Allele1 = col_character(),
                                            Tumor_Seq_Allele2 = col_character(),
                                            Reference_Allele = col_character(),
                                            Matched_Norm_Sample_Barcode = col_character(),
                                            n_ref_count = col_double(),
                                            n_depth = col_double(),
                                            n_alt_count = col_double(),
                                            Match_Norm_Seq_Allele1 = col_character(),
                                            Match_Norm_Seq_Allele2 = col_character()
                                            ))

GENIE_assay <- read_tsv("../../data/genie/Release_14.0_public/assay_information.txt")
```

# 2. genie panel choice
```{r GENIE panel choice}
# panel choice
Exon_panel <- c("DFCI-ONCOPANEL-1", "DFCI-ONCOPANEL-2", "DFCI-ONCOPANEL-3", "DFCI-ONCOPANEL-3.1", "MSK-IMPACT410", "MSK-IMPACT341", "MSK-IMPACT468", "MSK-IMPACT505", "DUKE-F1-DX1")
DFCI_panel <- c("DFCI-ONCOPANEL-1", "DFCI-ONCOPANEL-2", "DFCI-ONCOPANEL-3", "DFCI-ONCOPANEL-3.1")
MSK_panel <- c("MSK-IMPACT410", "MSK-IMPACT341", "MSK-IMPACT468", "MSK-IMPACT505")

print("GENIE samples of non-appropriate panel")
GENIE_non_app_samples <- GENIE_sample_file %>%
  filter(!(SEQ_ASSAY_ID %in% Exon_panel)) 
dim(GENIE_non_app_samples)[1]
# 66436→54634

print("GENIE samples of appropriate panel") 
GENIE_app_samples <- GENIE_sample_file %>%
  filter(SEQ_ASSAY_ID %in% Exon_panel)
dim(GENIE_app_samples)[1]
# 100659

## added for count---------------------------------
df_GENIE_clinical_sheet <- read_tsv("../../data/genie/Release_14.0_public/data_clinical_patient.txt", skip  = 4)
# All samples
nrow(df_GENIE_clinical_sheet)
df_GENIE_clinical_sheet %>% 
  count(PRIMARY_RACE)
## race at download---------------------------------

GENIE_precount <- GENIE_app_samples %>% 
  mutate(panel = ifelse(str_detect(SEQ_ASSAY_ID, "MSK"), "MSK",
                        ifelse(str_detect(SEQ_ASSAY_ID, "DFCI"), "DFCI",
                               ifelse(str_detect(SEQ_ASSAY_ID, "DUKE"), "DUKE", "other")))) %>% 
  count(panel) %>% 
  write_tsv(str_glue("{outdir_table}/1_sample_sheet/1_dataprep/GENIE_originalsamplecount.txt"))
print(GENIE_precount)

print("Number of removed mutations")
GENIE_mut_file %>%
  filter(!Tumor_Sample_Barcode %in% GENIE_app_samples$SAMPLE_ID) %>% 
  nrow()
# 458311→310810

print("Number of included mutations")
GENIE_mut_file_app_panel <- GENIE_mut_file %>%
  filter(Tumor_Sample_Barcode %in% GENIE_app_samples$SAMPLE_ID)
dim(GENIE_mut_file_app_panel)[1]
# 607496→754997

DFCI_sample <- GENIE_app_samples %>% filter(SEQ_ASSAY_ID %in% DFCI_panel)
MSK_sample <- GENIE_app_samples %>% filter(SEQ_ASSAY_ID %in% MSK_panel)
DUKE_sample <- GENIE_app_samples %>% filter(SEQ_ASSAY_ID %in% c("DUKE-F1-DX1"))

DFCI_sample_x1 <- DFCI_sample %>% nrow()
MSK_sample_x1 <- MSK_sample %>% nrow()
DUKE_sample_x1 <- DUKE_sample %>% nrow()
print(paste(DFCI_sample_x1, MSK_sample_x1, DUKE_sample_x1))

DFCI_x1 <- GENIE_mut_file_app_panel %>% filter(Tumor_Sample_Barcode %in% DFCI_sample$SAMPLE_ID) %>% nrow()
MSK_x1 <- GENIE_mut_file_app_panel %>% filter(Tumor_Sample_Barcode %in% MSK_sample$SAMPLE_ID) %>% nrow()
DUKE_x1 <- GENIE_mut_file_app_panel %>% filter(Tumor_Sample_Barcode %in% DUKE_sample$SAMPLE_ID) %>% nrow()

print(paste(DFCI_x1, MSK_x1, DUKE_x1))

#saved pre-filter counts
GENIE_precount_mut <- GENIE_mut_file_app_panel %>% 
    mutate(panel = ifelse(Tumor_Sample_Barcode %in% DFCI_sample$SAMPLE_ID, "DFCI", 
                        ifelse(Tumor_Sample_Barcode %in% MSK_sample$SAMPLE_ID, "MSK",
                               ifelse(Tumor_Sample_Barcode %in% DUKE_sample$SAMPLE_ID, "DUKE", "other")))) %>% 
  count(panel) %>% 
  write_tsv(str_glue("{outdir_table}/2_mutation_sheet/1_dataprep/GENIE_originalmutcount.txt"))
GENIE_precount_mut
```

# 3. VAF 
```{r remove samples without VAF}
########panel→sample に変更
#both not hotspot and more than 100 genes = "new panel"
GENIE_mut_file_app_panel %>% 
  filter(is.na(t_ref_count)) %>%
  dplyr::select(Tumor_Sample_Barcode) %>% 
  unique() -> GENIE_no_VAF_samples

print("GENIE samples with missing VAF information")
dim(GENIE_no_VAF_samples)[1]
#274 samples

print("Number of removed mutations")
GENIE_mut_file_app_panel %>%
  filter((Tumor_Sample_Barcode %in% GENIE_no_VAF_samples$Tumor_Sample_Barcode)) %>% 
  nrow()
#4051

print("Number of GENIE mutations")  #removed "no VAF samples" from mutation sheet
GENIE_mut_file_app_panel_VAF <- GENIE_mut_file_app_panel %>%
  filter(!(Tumor_Sample_Barcode %in% GENIE_no_VAF_samples$Tumor_Sample_Barcode))
nrow(GENIE_mut_file_app_panel_VAF)
#750946

print("Number of GENIE samples")  #keeping only samples with VAF from sample sheet
GENIE_app_samples_VAF <- GENIE_app_samples %>% 
  filter(!(SAMPLE_ID %in% GENIE_no_VAF_samples$Tumor_Sample_Barcode))
nrow(GENIE_app_samples_VAF)
#  81188
```

# 4. Primary/Metastasis

# 5. Serial samples
```{r removal of serial samples}
serial_samples <- GENIE_app_samples %>% 
  count(PATIENT_ID) %>%
  filter(n >= 2)
serial_samples %>% nrow() #6879

##################
GENIE_app_samples_VAF %>%
  filter(PATIENT_ID %in% serial_samples$PATIENT_ID) %>%
  mutate(number = if_else(str_detect(SEQ_ASSAY_ID, "DFCI"), str_extract(SAMPLE_ID, "[0-9]+$"),
                          if_else(str_detect(SEQ_ASSAY_ID, "MSK"), str_replace(str_replace(SAMPLE_ID, "GENIE-MSK-P-[0-9]+-T",""), "-[A-Z0-9]+$",""),
                                  if_else(str_detect(SEQ_ASSAY_ID, "DUKE"), str_extract(SAMPLE_ID, "[0-9]+$"), NA)))) %>% 
  filter(is.na(number))
#none

count_serial <- GENIE_app_samples_VAF %>%
  filter(PATIENT_ID %in% serial_samples$PATIENT_ID) %>%
  mutate(number = if_else(str_detect(SEQ_ASSAY_ID, "DFCI"), str_extract(SAMPLE_ID, "[0-9]+$"),
                          if_else(str_detect(SEQ_ASSAY_ID, "MSK"), str_replace(str_replace(SAMPLE_ID, "GENIE-MSK-P-[0-9]+-T",""), "-[A-Z0-9]+$",""),
                                  if_else(str_detect(SEQ_ASSAY_ID, "DUKE"), str_extract(SAMPLE_ID, "[0-9]+$"), NA)))) %>% 
  mutate(number = as.numeric(number)) %>% 
  group_by(PATIENT_ID) %>%
  arrange(number) %>%
  mutate(add_one = 1, num = cumsum(add_one)) %>%
  dplyr::select(-(add_one))

#save data to check----------------------
GENIE_app_samples_VAF %>%
  filter(PATIENT_ID %in% serial_samples$PATIENT_ID) %>%
  mutate(number = if_else(str_detect(SEQ_ASSAY_ID, "DFCI"), str_extract(SAMPLE_ID, "[0-9]+$"),
                          if_else(str_detect(SEQ_ASSAY_ID, "MSK"), str_replace(str_replace(SAMPLE_ID, "GENIE-MSK-P-[0-9]+-T",""), "-[A-Z0-9]+$",""),
                                  if_else(str_detect(SEQ_ASSAY_ID, "DUKE"), str_extract(SAMPLE_ID, "[0-9]+$"), NA)))) %>% 
  mutate(number = as.numeric(number)) %>% 
  group_by(PATIENT_ID) %>%
  arrange(number) %>%
  mutate(add_one = 1, num = cumsum(add_one)) %>%
  select(PATIENT_ID, SAMPLE_ID, AGE_AT_SEQ_REPORT, SEQ_ASSAY_ID, number, num, add_one) %>% 
  write_tsv(str_glue("{outdir_table}/1_sample_sheet/1_dataprep/GENIE_serialsample_numbering.txt"))
```

# 6. removal of serial samples
```{r removal of serial samples2}
count_serial %>% filter(num == 1) %>% ungroup() %>% count(SAMPLE_TYPE)
count_serial %>% filter(num >= 2) %>% ungroup() %>% count(SAMPLE_TYPE)

removal_sample <- count_serial %>% 
  filter(num >= 2)
print("Number of removed serial samples")
print(nrow(removal_sample))
#8158

removal_sample %>% 
  write_tsv(str_glue("{outdir_table}/1_sample_sheet/1_dataprep/GENIE_serialsamples_removed.txt"))

GENIE_app_samples_noserial <- GENIE_app_samples_VAF %>%
  filter(!SAMPLE_ID %in% removal_sample$SAMPLE_ID)

print("Number of samples")
nrow(GENIE_app_samples_noserial)
# 70645

print("Number of removed mutations")
GENIE_mut_file_app_panel %>%
  filter(!(Tumor_Sample_Barcode %in% GENIE_app_samples_noserial$SAMPLE_ID)) %>% 
  nrow()
#104339

print("Number of GENIE mutations")
GENIE_mut_file_app_panel_noserial <- GENIE_mut_file_app_panel_VAF %>%
  filter((Tumor_Sample_Barcode %in% GENIE_app_samples_noserial$SAMPLE_ID))
nrow(GENIE_mut_file_app_panel_noserial)
# 745856→ 650658 →650552→668589
```

# 7. count 
```{r}
print("number of samples removed by panel")
GENIE_app_samples_noserial %>% 
  mutate(panel = ifelse(str_detect(SEQ_ASSAY_ID, "MSK"), "MSK",
                        ifelse(str_detect(SEQ_ASSAY_ID, "DFCI"), "DFCI",
                               ifelse(str_detect(SEQ_ASSAY_ID, "DUKE"), "DUKE", "other")))) %>% 
  count(panel)

print("number of mutations removed by panel")
GENIE_mut_file_app_panel_noserial %>%
  filter((Tumor_Sample_Barcode %in% GENIE_no_VAF_samples$Tumor_Sample_Barcode)) %>% 
  mutate(panel = ifelse(str_detect(Tumor_Sample_Barcode, "MSK"), "MSK",
                        ifelse(str_detect(Tumor_Sample_Barcode, "DFCI"), "DFCI",
                               ifelse(str_detect(Tumor_Sample_Barcode, "DUKE"), "DUKE", "other")))) %>% 
  count(panel)

DFCI_sample_x2 <- GENIE_app_samples_noserial %>% filter(SEQ_ASSAY_ID %in% DFCI_panel) %>% nrow()
MSK_sample_x2 <- GENIE_app_samples_noserial %>% filter(SEQ_ASSAY_ID %in% MSK_panel) %>% nrow()
DUKE_sample_x2 <- GENIE_app_samples_noserial %>% filter(SEQ_ASSAY_ID %in% "DUKE-F1-DX1") %>% nrow()
print("original sample number")
print(paste(DFCI_sample_x1, MSK_sample_x1, DUKE_sample_x1))
print("remaining sample number")
print(paste(DFCI_sample_x2, MSK_sample_x2, DUKE_sample_x2))

DFCI_x2 <- GENIE_mut_file_app_panel_noserial %>%
  filter(Tumor_Sample_Barcode %in% DFCI_sample$SAMPLE_ID) %>% 
  nrow()
MSK_x2 <- GENIE_mut_file_app_panel_noserial %>%
  filter(Tumor_Sample_Barcode %in% MSK_sample$SAMPLE_ID) %>% 
  nrow()
DUKE_x2 <- GENIE_mut_file_app_panel_noserial %>%
  filter(Tumor_Sample_Barcode %in% DUKE_sample$SAMPLE_ID) %>% 
  nrow()

print("original mutation number")
print(paste(DFCI_x1, MSK_x1, DUKE_x1))
print("remaining mutation number")
print(paste(DFCI_x2, MSK_x2, DUKE_x2))

print("removed samples and mutations")
print(paste(DFCI_sample_x1 - DFCI_sample_x2, MSK_sample_x1 - MSK_sample_x2, DUKE_sample_x1 - DUKE_sample_x2))
print(paste(DFCI_x1 - DFCI_x2, MSK_x1 - MSK_x2, DUKE_x1 - DUKE_x2))
```

# 8. select variables
```{r select variables}
GENIE_mut_file_app_panel_noserial_select <- GENIE_mut_file_app_panel_noserial %>%
  dplyr::select(Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand,  
           Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele2, Tumor_Sample_Barcode, Matched_Norm_Sample_Barcode,
           HGVSc, HGVSp_Short, Exon_Number, t_depth, t_ref_count, t_alt_count, Transcript_ID) 
```

# 9. Save sample sheet and mutation sheet
```{r output}
# write output
nrow(GENIE_app_samples_noserial)
nrow(GENIE_mut_file_app_panel_noserial_select)
# 89814

GENIE_app_samples_noserial %>%
  write_tsv(str_glue("{outdir_table}/1_sample_sheet/1_dataprep/GENIE_samplefile.txt"))

GENIE_mut_file_app_panel_noserial_select %>%
  write_tsv(str_glue("{outdir_table}/2_mutation_sheet/1_dataprep/GENIE_mutation_mutfile.txt"))
```

# prev script
```{r remove samples without primary metastasis information}
# # remove samples without primary/metastasis information
# print("GENIE samples without primary/metastasis information")
# GENIE_app_samples_VAF %>% 
#   filter(SAMPLE_TYPE != "Primary" & SAMPLE_TYPE != "Metastasis") %>% 
#   nrow()
# #2385
# 
# print("GENIE samples with primary/metastasis information") #overwrite to only samples with primary/meta data
# GENIE_app_samples_primarymeta <- GENIE_app_samples_VAF %>% 
#   filter(SAMPLE_TYPE == "Primary" | SAMPLE_TYPE == "Metastasis") 
# nrow(GENIE_app_samples_primarymeta)
# #78803
# 
# print("Number of removed mutations")
# GENIE_mut_file_app_panel_VAF %>%
#   filter(!(Tumor_Sample_Barcode %in% GENIE_app_samples_primarymeta$SAMPLE_ID)) %>% 
#   nrow()
# # 21075
# 
# print("Number of GENIE mutations") #keeping samples included in GENIE_app_samples (info on tumor meta/primary)
# GENIE_mut_file_app_panel_primarymeta <- GENIE_mut_file_app_panel_VAF %>%
#   filter((Tumor_Sample_Barcode %in% GENIE_app_samples_primarymeta$SAMPLE_ID))
# nrow(GENIE_mut_file_app_panel_primarymeta)
# # [1]  729871
```

```{r}
sessionInfo()
```





