---
title: "1_tcga_datareadin"
author: "Sara Horie"
date: "2022/9/5"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r library}
library(tidyverse)
library(dplyr)
library(readxl)
library(RColorBrewer)
library(viridis)
library(knitr)
library(cowplot)
library(ggplot2)
library(devtools)
library(ggpubr)
library(rstatix)
library(ggrepel)
library(openxlsx)
library(data.table)
library(ggsci)
library(readxl)
library(ggsci)
```

```{r theme}
theme_set(theme_cowplot())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
dir.create("result/3_tcga/table/1_dataprep/1_sample_sheet/1_dataprep/", recursive = TRUE, showWarnings = FALSE)
dir.create("result/3_tcga/table/1_dataprep/2_mutation_sheet/1_dataprep/", recursive = TRUE, showWarnings = FALSE)
# dir.create("result/3_tcga/table/1_dataprep/2_mutation_sheet/5_TMB_MSI/", recursive = TRUE, showWarnings = FALSE)
dir.create("result/3_tcga/pdf/1_dataprep/TMB_MSI/", recursive = TRUE, showWarnings = FALSE)
```

https://gdc.cancer.gov/about-data/publications/pancanatlas
Mutations - mc3.v0.2.8.PUBLIC.maf.gz

# 1, TCGA readin
## 1.1 tcga public
```{r}
df_tcga_public <- read_tsv("../../data/tcga/mc3.v0.2.8.PUBLIC.maf")
dim(df_tcga_public)

mc3_sample <- read_excel("../../data/tcga/TCGA-CDR-SupplementalTableS1.xlsx",
                         sheet = "TCGA-CDR") %>% 
  select(-`...1`)

tcga_sample_df_all <- read_tsv("../../data/tcga/merged_sample_quality_annotations.tsv") 
nrow(tcga_sample_df_all)
```

## 1.2  read in sample data using tcga public mut file (MUT FILE samples!)
```{r}
nrow(df_tcga_public %>% filter(is.na(t_ref_count)))
nrow(df_tcga_public %>% filter(is.na(t_alt_count)))
nrow(df_tcga_public %>% filter(is.na(t_depth)))

# no samples with no vaf info
tcga_mut_sample_ids <- df_tcga_public %>%
  select(Tumor_Sample_Barcode) %>% 
  distinct(Tumor_Sample_Barcode) %>%
  mutate(Patient_Barcode = str_extract(Tumor_Sample_Barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+")) %>%
  mutate(Tumor_Sample_ID = str_extract(Tumor_Sample_Barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9]+")) %>%
  mutate(Tumor_Lysate_ID = str_extract(Tumor_Sample_Barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9A-Z2]+-[0-9]+"))

tcga_mut_sample_ids %>% 
  write_tsv("result/3_tcga/table/1_dataprep/1_sample_sheet/1_dataprep/tcga_sample_names_public_ids.txt")
```


```{r}
# pull out sample num
tcga_mut_sample_ids <- tcga_mut_sample_ids %>% 
   mutate(sample_num = as.numeric(str_sub(Tumor_Sample_ID, nchar(Tumor_Sample_ID) - 1, nchar(Tumor_Sample_ID))))
unique(tcga_mut_sample_ids$sample_num)
# [1] 1 2 5 6 3 

head(tcga_mut_sample_ids)
X1 <- nrow(tcga_mut_sample_ids)

tcga_mut_sample_ids %>% 
  group_by(Patient_Barcode) %>% 
  # filter(n() > 1) %>%
  arrange(sample_num) %>% 
  mutate(num = row_number()) %>% 
  summarise(multiple_samples = paste(sample_num, collapse = ";")) %>% 
  distinct(multiple_samples)

#   multiple_samples
#   <chr>           
# 1 1               
# 2 1;2             
# 3 1;5             
# 4 6               
# 5 2               
# 6 3               
# 7 1;6             
# 8 1;5;6  

# multiple_samples some samples have both primary and recurrent samples. all multiple samples have a 01 sample (primary solid)
# 01	Primary Solid Tumor	TP
# 02	Recurrent Solid Tumor	TR
# 03	Primary Blood Derived Cancer - Peripheral Blood	TB
# 04	Recurrent Blood Derived Cancer - Bone Marrow	TRBM
# 05	Additional - New Primary	TAP
# 06	Metastatic	TM
# 07	Additional Metastatic	TAM

#check dups (double check with sample_num and row number)
tcga_mut_sample_ids %>% 
  group_by(Patient_Barcode) %>% 
  arrange(sample_num) %>% 
  mutate(num = row_number()) %>% 
  filter(n() > 1) %>% 
  arrange(Patient_Barcode, num) %>% 
  write_tsv("result/3_tcga/table/1_dataprep/1_sample_sheet/1_dataprep/tcga_sample_names_dup.txt")

print("remove duplicates")
tcga_mut_sample_ids_nodup <- tcga_mut_sample_ids %>% 
  group_by(Patient_Barcode) %>% 
  arrange(sample_num) %>% 
  mutate(num = row_number()) %>% 
  filter(num == 1)

tcga_mut_sample_ids %>% 
  group_by(Patient_Barcode) %>% 
  filter(sample_num %in% c(1, 3))

X2 <- nrow(tcga_mut_sample_ids_nodup)
print("dup samples removed")
X1 - X2
#71

#before and after dup removal
print(X1)
print(X2)

# check: none have 2 samples after filter
tcga_mut_sample_ids_nodup %>% 
  group_by(Patient_Barcode) %>% 
  # filter(n() > 1) %>%
  arrange(sample_num) %>% 
  mutate(num = row_number()) %>% 
  summarise(multiple_samples = paste(sample_num, collapse = ";")) %>% 
  count(multiple_samples)
```

## 1.3 TCGA QC and MC3 (SAMPLE FILE)
```{r}
# 11276 distinct patient barcodes in QC file
length(unique(tcga_sample_df_all$patient_barcode))

# 11160 samples in mc3 sample
length(unique(mc3_sample$bcr_patient_barcode))

length(setdiff(tcga_mut_sample_ids$Patient_Barcode, c(tcga_sample_df_all$patient_barcode, mc3_sample$bcr_patient_barcode)))
# 3 not in either sample sheet
```

# 2.0 QC and mc3 sample file prep: remove FPPP
```{r}
# create distinct sample info
# remove FPPP samples
tcga_sample_qc_distinct <- tcga_sample_df_all %>% 
  filter(`cancer type` != "FPPP") %>% 
  distinct(patient_barcode, `cancer type`)
nrow(tcga_sample_qc_distinct)

tcga_sample_qc_distinct %>%
  group_by(patient_barcode) %>% 
  filter(n() > 1)
# TCGA-07-0227 has 4 different cancer types, but is not included in the mutation file
# 11279

# remove, although not in mut file anyway
tcga_sample_qc_distinct <- tcga_sample_qc_distinct %>% 
  filter(patient_barcode != "TCGA-07-0227")

mc3_sample %>%
  group_by(bcr_patient_barcode) %>% 
  filter(n() > 1)
# no multiple patient barcode rows in mc3

print("check to see if cancer types match")
tcga_sample_qc_distinct %>% 
  left_join(mc3_sample, by = c("patient_barcode" = "bcr_patient_barcode")) %>% 
  filter(!is.na(type)) %>% 
  filter(`cancer type` != type)
# no unmatching cancer types in mc3 and qc files
```

# 3.0 do not use: QC and redacted in MC3
```{r }
print("QC file") 
tcga_sample_df_all %>% 
  count(platform)

donotuse <- tcga_sample_df_all %>% 
  filter(platform == "IlluminaHiSeq_DNASeqC") %>% 
  filter(Do_not_use)
nrow(donotuse)
donotuse 
# 23 pairs! of tumor and normal. total 46 

print("MC3")
redacted <- mc3_sample %>% 
  filter(Redaction == "Redacted")

#-------
# some samples use different portion of same sample for QC
donotuse %>% filter(patient_barcode == "TCGA-44-6147")
 # TCGA-44-6147-01A-11D-1751-02 
tcga_mut_sample_ids %>% filter(Patient_Barcode == "TCGA-44-6147")
 # TCGA-44-6147-01A-31D-A27T-08
```

# 4.0 make sample file! from mut file distinct samples
```{r}
df_tcga_mc3_qc <- tcga_mut_sample_ids_nodup %>% 
  ungroup() %>% 
  left_join(tcga_sample_qc_distinct, by = c("Patient_Barcode" = "patient_barcode")) %>% 
  left_join(mc3_sample, by = c("Patient_Barcode" = "bcr_patient_barcode")) %>% 
  filter(!is.na(`cancer type`) | !is.na(type)) %>% 
  mutate(`cancer type` = if_else(is.na(`cancer type`), type, `cancer type`))

df_tcga_mc3_qc
stopifnot(nrow(tcga_mut_sample_ids_nodup) == nrow(tcga_mut_sample_ids_nodup %>% ungroup() %>% 
  left_join(tcga_sample_qc_distinct, by = c("Patient_Barcode" = "patient_barcode")) %>% 
  left_join(mc3_sample, by = c("Patient_Barcode" = "bcr_patient_barcode"))))

X3 <- nrow(df_tcga_mc3_qc)
print(X3)
X2 - X3
# samples not in either MC3 or QC file!!
```

# sample check
```{r}
# tmpdna_qc <- df_dna_qc %>% 
#   mutate(Tumor_Sample_ID = str_extract(aliquot_barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9]+")) %>% 
#   mutate(Tumor_Lysate_ID = str_extract(aliquot_barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9A-Z2]+-[0-9]+"))
# 
# qc_fail <- df_dna_qc %>% 
#   mutate(Tumor_Sample_ID = str_extract(aliquot_barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9]+")) %>% 
#   mutate(Tumor_Lysate_ID = str_extract(aliquot_barcode, "TCGA-[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9A-Z2]+-[0-9]+")) %>% 
#   filter(Do_not_use)
# 
# df_dna_qc <- tcga_sample_df_all %>% 
#   filter(platform == "IlluminaHiSeq_DNASeqC")
# 
# length(intersect(tcga_mut_sample_ids_nodup$Patient_Barcode, df_dna_qc$patient_barcode)) #1173
# length(intersect(tcga_mut_sample_ids_nodup$Tumor_Sample_Barcode, df_dna_qc$aliquot_barcode)) #0 
# length(intersect(tcga_mut_sample_ids_nodup$Tumor_Sample_ID, tmpdna_qc$Tumor_Sample_ID)) # 1054
```


```{r}
# df_dna_qc %>% 
#   group_by(patient_barcode) %>% 
#   summarise(all = paste(Do_not_use, collapse = ";"), samplenames = paste(aliquot_barcode, collapse = ";")) %>% 
#   filter(str_detect(all, "TRUE"))
# 
# # TCGA-GN-A261	TRUE;TRUE	TCGA-GN-A261-10A-01D-A190-02;TCGA-GN-A261-06A-12D-A18Y-02		
# # TCGA-HR-A2OG	FALSE;TRUE	TCGA-HR-A2OG-10A-01D-A190-02;TCGA-HR-A2OG-01A-21D-A18Y-02		tumor "donotuse"
# # TCGA-HR-A2OH	FALSE;TRUE	TCGA-HR-A2OH-10A-01D-A190-02; TCGA-HR-A2OH-01A-11D-A18Y-02  tumor "donotuse"
# 
# tcga_mut_sample_ids_nodup %>% 
#   filter(Patient_Barcode == "TCGA-HR-A2OH")
# # TCGA-HR-A2OH-06A-11D-A197-08 (mut) vs TCGA-HR-A2OH-01A-11D-A18Y-02 (QC)
# # Notification:Acceptable treatment for TCGA tumor:Patient received interferon for the specimen submitted to TCGA
# # would not be removed with tumor sample ID! 
# 
# tcga_mut_sample_ids_nodup %>% 
#   filter(Patient_Barcode == "TCGA-HR-A2OG")
# # TCGA-HR-A2OG-06A-21D-A197-08 vs TCGA-HR-A2OG-01A-21D-A18Y-02 "06" 
# # Notification:Barcode incorrect:Originally identified as primary solid tumor, reclassified as metastatic.  Data associated with this barcode will be transitioned to the correct barcode.  Correct barcode is TCGA-HR-A2OG-06A-21D-A18Y-02
# # difficult to differentiate each sample, on whether this sample should be removed or not if not matching tumor sample barcode. 
# 
# tcga_mut_sample_ids_nodup %>% 
#      filter(Patient_Barcode %in% c(donotuse$patient_barcode))
# 
# tcga_mut_sample_ids_nodup %>% 
#      filter(Tumor_Sample_ID %in% qc_fail$Tumor_Sample_ID)
```

# 5.0 
```{r }
print("QC okay samples only")
tcga_sample_df_QCokay <- df_tcga_mc3_qc %>% 
  filter(!Patient_Barcode %in% c(donotuse$patient_barcode, redacted$bcr_patient_barcode))
# 20 with do not use
# mc3 sample qc only has patient barcode id. used patient barcode for QC fail samples for QC sample sheet. 
# some samples would not be correctly removed with only tumor sample id matching. ex) "TCGA-HR-A2OH"

X4 <- nrow(tcga_sample_df_QCokay)
print("removed with do not use")
X3 - X4

print("final removed samples")
X1 - X4
# 54

# check
tcga_sample_df_QCokay %>% filter(is.na(`cancer type`) & is.na(type)) %>% nrow()
tcga_sample_df_QCokay %>% filter(`cancer type` == "FPPP") %>% nrow()
tcga_sample_df_QCokay %>% filter(Patient_Barcode %in% c(donotuse$patient_barcode, redacted$bcr_patient_barcode))
# 0 samples
```


# 6.0 save
```{r}
tcga_sample_df_QCokay %>% 
  write_tsv("result/3_tcga/table/1_dataprep/1_sample_sheet/1_dataprep/tcga_samplesheet.txt")

nrow(tcga_sample_df_QCokay)
# 10167

tcga_sample_df_QCokay %>% 
  count(`cancer type`)
tcga_sample_df_QCokay %>% 
  count(`cancer type`, type) %>% 
  filter(is.na(type))
```

```{r}
sessionInfo()
```

